### ISSUE TITLE
hand-crafted prompts

### ISSUE THREAD

**Issue by Lyan-ing** [kdiAAA/TDA#2]
Interesting work. 
Do you have any experimental data without  "hand-crafted prompts"? i dont foud this in ablation studies.

**Comment by kdiAAA** [comment]
Hello, thank you for your interest in our work, and I am sorry for the late reply; I was on vacation. In our ablation studies, we did not perform tests without "hand-crafted prompts" as they are integral to our methodology.

Hope this helps clarify your queries!

Best,
Adilbek
