### ISSUE TITLE
The config file `configs/dataset.yaml` is absent

### ISSUE THREAD

**Issue by auniquesun** [kdiAAA/TDA#3]
Thanks for sharing the paper and code. It is a great work.

However, after reading the code, I found that an important config file `configs/dataset.yaml` is absent, could you also share it? 

Thanks.

**Comment by kdiAAA** [comment]
Hello,

Thank you for your interest in our work and apologies for the late reply; I was on vacation. I apologize for any confusion regarding the config files. In our repository, under the `configs` folder, you will find the specific config files we used for each dataset in our study. If you're looking to test the method on other datasets, I recommend using the config file for the ImageNet dataset, named `imagenet.yaml`.

Hope this helps clarify your query!

Best,
Adilbek
