### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by jingdu-cs** [kdiAAA/TDA#4]
Hi,

Thank you for sharing your codebase, it's really helpful. However, it appears that the important `requirements.txt` file is missing. Could you please provide the versions of the related packages?

Many thanks!

**Comment by kdiAAA** [comment]
Hello,

Thank you for your interest in our work and I apologize for the late reply; I was on vacation. I apologize for the oversight regarding the `requirements.txt` file. It has now been uploaded to the codebase. 

Thank you for bringing this to my attention!

Best,
Adilbek
